feature/CU-jx9k5x_BACK-END-Add-quiz-creation-service
Horsemen-and-Women-of-the-Apocalypse/quiz-backend pull request #10
Opened 2021-05-18 17:16 UTC by YesLife

2021-05-18 17:16 UTC, YesLife commented
Task linked: [CU-jx9k5x [BACK-END] Add quiz creation service](https://app.clickup.com/t/jx9k5x)

2021-05-18 17:31 UTC, Thurstag requested changes

2021-05-18 17:31 UTC, Thurstag commented on src/services/db/db.js
>          let collectionsCursor = await this.db.listCollections();
appliquer le fix ici aussi

2021-05-18 17:43 UTC, YesLife commented on src/services/db/db.js
>          let collectionsCursor = await this.db.listCollections();
Je l'ai supprimé car inutile (la création d'une collection est induite par son ajout)

2021-05-18 17:58 UTC, Thurstag commented on src/services/db/db.js
>          let collectionsCursor = await this.db.listCollections();
effectivement

2021-05-19 11:19 UTC, Thurstag approved these changes

2021-05-19 11:19 UTC, Thurstag approved these changes

2021-05-19 11:28 UTC, Fantorem approved these changes

2021-05-19 13:00 UTC, furtivesock approved these changes

2021-05-19 13:12 UTC, merged