feature/CU-jvc2ba_BACK-END-Lobby-joining-entry-point
Horsemen-and-Women-of-the-Apocalypse/quiz-backend pull request #16
Opened 2021-05-19 21:46 UTC by Tomansion

2021-05-19 21:46 UTC, Tomansion commented
Task linked: [CU-jvc2ba [BACK-END] Lobby joining entry point](https://app.clickup.com/t/jvc2ba)

2021-05-19 21:49 UTC, Tomansion commented on test/common/utils.js
> +    return l;
c'est un L, pas un 1

2021-05-19 21:55 UTC, Tomansion commented
J'ai mis en draft car j'ai oublié d'implémenter les room ws

2021-05-19 21:55 UTC, YesLife approved these changes

2021-05-19 22:35 UTC, LeBoyLeoz approved these changes

2021-05-20 06:59 UTC, Thurstag requested changes

2021-05-20 06:59 UTC, Thurstag commented on src/services/ws.js
> +            socket.data = {};
Pas utile. En plus attacher des données à une classe que l'on ne maitrise pas c'est pas génial

2021-05-20 06:59 UTC, Thurstag commented on src/services/ws.js
> +        const player = lobby.players.find(p => p.id === query.playerId);
Attention le frontend va t'envoyer un player id de type string donc ton check va pas marcher

2021-05-20 06:59 UTC, Thurstag commented on src/services/ws.js
> +        if (!query || !query.playerId) throw new AuthError(AUTH.ACCESS_DENIED + " a playerId is requiered");
`required`

2021-05-20 06:59 UTC, Thurstag commented on src/services/ws.js
> +        if (!query.lobbyId) throw new AuthError(AUTH.ACCESS_DENIED + " a lobbyId is requiered");
`required`

2021-05-20 07:33 UTC, Tomansion commented on src/services/ws.js
> +        const player = lobby.players.find(p => p.id === query.playerId);
p.id est un guid de type string

2021-05-20 07:35 UTC, Tomansion commented on src/services/ws.js
> +        const player = lobby.players.find(p => p.id === query.playerId);
uuid*

2021-05-20 07:36 UTC, Thurstag commented on src/services/ws.js
> +        const player = lobby.players.find(p => p.id === query.playerId);
ah j'ai confondu avec les id mongodb, mb

2021-05-20 07:42 UTC, LeBoyLeoz approved these changes

2021-05-20 08:36 UTC, Thurstag approved these changes

2021-05-20 08:36 UTC, merged