feature/CU-jvab5f_BACK-END-Save-quizzes-on-quizzes-collection-creation
Horsemen-and-Women-of-the-Apocalypse/quiz-backend pull request #17
Opened 2021-05-19 22:59 UTC by YesLife

2021-05-19 22:59 UTC, YesLife commented
Task linked: [CU-jvab5f [BACK-END] Save quizzes on quizzes collection creation](https://app.clickup.com/t/jvab5f)

2021-05-20 06:49 UTC, Thurstag requested changes

2021-05-20 06:49 UTC, Thurstag commented on src/services/db/db.js
> +        return collectionNames.indexOf(collection) >= 0;
C'est pas `return collectionNames.indexOf(collection) < 0;` ?

2021-05-20 08:28 UTC, Thurstag approved these changes

2021-05-20 08:29 UTC, Tomansion approved these changes

2021-05-20 11:56 UTC, Fantorem approved these changes

2021-05-20 11:56 UTC, merged