Feature/cu jvaz44 back end define lobby model
Horsemen-and-Women-of-the-Apocalypse/quiz-backend pull request #7
Opened 2021-05-17 20:21 UTC by Tomansion

2021-05-17 20:21 UTC, Thurstag commented
Task linked: [CU-jvaz44 [BACK-END] Define lobby model](https://app.clickup.com/t/jvaz44)

2021-05-18 07:47 UTC, Tomansion commented
seul le commit 
https://github.com/Horsemen-and-Women-of-the-Apocalypse/quiz-backend/pull/7/commits/898b75907227aee7219c15a621f7eb79567183b8 
est à revoir

2021-05-18 07:55 UTC, Thurstag requested changes

2021-05-18 07:55 UTC, Thurstag commented on src/models/lobby.js
> + * Lobby class
Doc mal placé

2021-05-18 07:55 UTC, Thurstag commented on src/models/lobby.js
> +    get players() { return [ this.owner, ...this._otherPlayers ]; }
Documentes le fait qu'il y a le owner dedans.

2021-05-18 07:55 UTC, Thurstag commented on src/models/lobby.js
> +        this.startDate = moment().format("MMMM Do YYYY, h:mm:ss a");
Format à sortir dans une constante, tu peux faire une méthode statique car on va devoir parser les dates provenant de la base de données.

2021-05-18 07:55 UTC, Thurstag commented on src/models/lobby.js
> +    constructor(name, quiz, owner, players) {
Si on charge un lobby de la base il faut un moyen pour charger les dates dans la classe

2021-05-18 08:24 UTC, Thurstag requested changes

2021-05-18 08:24 UTC, Thurstag commented on test/models/player.spec.js
> +describe("Lobby", () => {
Player

2021-05-18 09:15 UTC, Thurstag requested changes

2021-05-18 09:15 UTC, Thurstag commented on src/models/lobby.js
> +    constructor(name, quiz, owner, players, startDate=null, endDate=null) {
Il faut vérifier le type de startDate, endDate si ils ne sont pas null

2021-05-18 09:15 UTC, Thurstag commented on src/models/lobby.js
> +    constructor(name, quiz, owner, players, startDate=null, endDate=null) {
Il manque answersByPlayerId en paramètre + check type

2021-05-18 10:17 UTC, Thurstag requested changes

2021-05-18 10:17 UTC, Thurstag commented on src/models/lobby.js
> +            if (typeof answersByPlayerId[prop] !== "object") throw new Error("Expected an object for the answersByPlayerId value");
ça doit être une array pas un object + il faut vérifier que prop est de type string

2021-05-18 10:30 UTC, Tomansion commented on src/models/lobby.js
> +            if (typeof answersByPlayerId[prop] !== "object") throw new Error("Expected an object for the answersByPlayerId value");
je vérifie aussi le contenu du tableau ?

pour prop : j'avais fait la vérif à l'époque, mais la clé, même si on met un nombre, sera un string

2021-05-18 10:35 UTC, Thurstag commented on src/models/lobby.js
> +            if (typeof answersByPlayerId[prop] !== "object") throw new Error("Expected an object for the answersByPlayerId value");
Dac je savais pas pour prop. Pas besoin de vérifier le contenu du tableau

2021-05-18 12:03 UTC, Thurstag approved these changes

2021-05-18 12:59 UTC, YesLife approved these changes

2021-05-18 13:11 UTC, furtivesock approved these changes

2021-05-18 13:11 UTC, merged