feature/CU-jv91ta_BACK-END-Questions-entry-point
Horsemen-and-Women-of-the-Apocalypse/quiz-backend pull request #9
Opened 2021-05-18 15:14 UTC by furtivesock

C'est temporaire parce que je n'ai pas encore pris en compte le `QuizService`. Mais n'hésitez pas à partager vos premières impressions !

2021-05-18 15:14 UTC, Thurstag commented
Task linked: [CU-jv91ta [BACK-END] Questions entry point](https://app.clickup.com/t/jv91ta)

2021-05-18 15:31 UTC, Thurstag requested changes

2021-05-18 15:31 UTC, Thurstag commented on src/common/errors.js
> +    FILE_SIZE_REACHED: "HTTP_FILE_SIZE_REACHED"
Pas utilisé

2021-05-18 15:31 UTC, Thurstag commented on src/router/routes/version/quiz/index.js
> +    "quiz-creation": new Route(route => route, "create", create),
La route est pas bonne ainsi que la méthode HTTP

2021-05-18 15:31 UTC, Thurstag commented on src/router/routes/version/quiz/index.js
> +        response.json(new Response((await services.quiz.all()).map(QuizService.ToAPIObject)));
tu comptes renvoyer toutes les quizzes avec les réponses et tout ? cf. ticket pour ce qui faut renvoyer

2021-05-18 15:31 UTC, Thurstag commented on src/router/routes/version/quiz/index.js
> +        await services.quiz.create(request.body);
Il faudra rajouter des checks car là on sauvegarde ce que l'utilisateur envoie donc il peut y avoir n'importe quoi

2021-05-18 15:31 UTC, Thurstag commented on test/test-utils/server.js
> +const QUIZ_CREATE_ROUTE = "/quiz/";
"/quiz/create"

2021-05-18 15:31 UTC, Thurstag commented on test/integration/quiz.spec.js
> +    beforeEach(done => {
Pourquoi créer un quiz avant chaque test ?

2021-05-18 15:31 UTC, Thurstag commented on test/integration/quiz.spec.js
> +        database.close();
La fermeture de la database c'est géré dans hooks donc rien à faire ici (Tu vas faire planter d'autres tests)

2021-05-18 15:31 UTC, Thurstag commented on test/integration/quiz.spec.js
> +        initAndReset()
Tu en as besoin ?

2021-05-18 15:31 UTC, Thurstag commented on test/integration/quiz.spec.js
> +        reset().then(() => done()).catch(done);
Tu en as besoin ?

2021-05-18 15:31 UTC, Thurstag commented on src/router/routes/version/quiz/index.js
> + * Function that defines a callback on /
Function that defines a callback on /create

2021-05-18 15:31 UTC, Thurstag commented on src/router/routes/version/quiz/index.js
> +        response.json(new Response((await services.quiz.questions()).map(QuizService.ToAPIObject)));
Il faudra utiliser l'id dans l'url

2021-05-18 15:31 UTC, Thurstag commented on src/router/routes/version/quiz/index.js
> +        response.json(new Response((await services.quiz.answer(request.body)).map(QuizService.ToAPIObject)));
Il faudra utiliser l'id dans l'url + faire des checks sur body pour voir si il a le format que l'on a définie

2021-05-18 15:31 UTC, Thurstag commented on test/integration/quiz.spec.js
> +chai.use(require("chai-http"));
Pas besoin c'est fait dans les hooks

2021-05-18 15:31 UTC, Thurstag commented on test/integration/quiz.spec.js
> +            const quiz = await quiz_service.getById(2);
Très peu probable que le quiz qui vient d'être créé possède l'id 2. Une idée ce serait que l'API retourne l'ID du quiz si elle a réussi à en créer un.

2021-05-18 15:41 UTC, furtivesock commented on src/router/routes/version/quiz/index.js
> +        response.json(new Response((await services.quiz.all()).map(QuizService.ToAPIObject)));
My bad je viens de m'en rappeler !

2021-05-18 17:43 UTC, furtivesock commented on src/router/routes/version/quiz/index.js
> +        await services.quiz.create(request.body);
D'accord, je pensais que c'était la méthode `create` qui s'en chargeait.

2021-05-18 17:48 UTC, furtivesock commented on test/integration/quiz.spec.js
> +        reset().then(() => done()).catch(done);
Oui pour réinitialiser la base ? Ou je me trompe ?

2021-05-18 17:52 UTC, furtivesock commented on src/common/errors.js
> +    FILE_SIZE_REACHED: "HTTP_FILE_SIZE_REACHED"
J'utilisais `HTTP.BODY_UNDEFINED` pour la méthode `POST`, je retire quand même toutes ces constantes d'erreur ?

2021-05-18 17:58 UTC, Thurstag commented on test/integration/quiz.spec.js
> +        reset().then(() => done()).catch(done);
Dans repowee le reset sert à reset la base, ici cette fonction n'existe pas. Est-ce que dans tes tests tu penses que tu as besoin de reset la base ? Cette branche c'est l'entry point des questions donc si j'avais à le faire:
- Je créée un quiz au début de mes tests
- J'utilise le quiz créé pour faire mes tests.

N.B: Quand je dis "est-ce que tu as besoin de reset" c'est dans le sens: est-ce qu'il existe un test dont tu as besoin qui a besoin obligatoirement d'un reset de la base car si c'est pas utile autant ne pas le faire.

2021-05-18 18:01 UTC, Thurstag commented on src/common/errors.js
> +    FILE_SIZE_REACHED: "HTTP_FILE_SIZE_REACHED"
Non c'est une bonne idée. L'intérêt des commentaires de PR c'est qu'ils sont attachés à une ligne donc mon commentaire porte sur FILE_SIZE_REACHED qui est inutile (c'est peu probable que l'on rencontre ce type d'erreur et tu ne l'utilises pas) et non pas sur toute la structure.

2021-05-19 11:21 UTC, Thurstag commented
A refaire

2021-05-19 11:21 UTC, closed without merging